name: Build
on:
  push:
    branches: ["*"]
    paths-ignore:
      - "**/docs/**"
      - "**.md"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: sassman/.github/.github/workflows/build.yml@main

  coverage:
    name: code coverage
    uses: sassman/.github/.github/workflows/coverage.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
