name: Coverage
on:
  push:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  coverage:
    name: code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: sassman/.github/.github/actions/rust-toolchain@main
        with:
          channel: nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --features dangerous --no-default-features --workspace --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: codecov.json
          verbose: true
          fail_ci_if_error: false
