name: Coverage
on:
  push:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  coverage:
    name: code coverage
    strategy:
      fail-fast: false
      matrix:
        coverage-cmd:
          - llvm-cov
          - llvm-cov --features doc-test-mocks
          - llvm-cov --features dangerous --no-default-features
          - llvm-cov --features hash-sha1 --no-default-features
          - llvm-cov --features wow --no-default-features
          - llvm-cov --features hash-sha512 --no-default-features
      max-parallel: 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: sassman/.github/.github/actions/rust-toolchain@main
        with:
          channel: nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo ${{ matrix['coverage-cmd'] }} --workspace --codecov --output-path codecov-$(uuidgen).json
      - name: collect all coverage files into a comma separeted list
        run: echo "coverage_files=$(ls -1 codecov*.json | tr '\n' ',')" >> $GITHUB_ENV
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ${{ env.coverage_files }}
          verbose: true
          fail_ci_if_error: false
